import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'ru' | 'be';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ru: {
    catalog: 'Каталог',
    about: 'О нас',
    reviews: 'Отзывы',
    contacts: 'Контакты',
    cart: 'Корзина',
    addToCart: 'В корзину',
    checkout: 'Оформить заказ',
    emptyCart: 'Ваша корзина пуста',
    total: 'Итого',
    currency: 'BYN',
    backToCatalog: 'Назад в каталог',
    notFound: 'Товар не найден',
    search: 'Поиск ароматов...',
    allBrands: 'Все бренды',
    sortNameAsc: 'Название (А-Я)',
    sortNameDesc: 'Название (Я-А)',
    sortPriceAsc: 'Сначала дешевле',
    sortPriceDesc: 'Сначала дороже',
    genderAll: 'Все',
    genderMale: 'Мужские',
    genderFemale: 'Женские',
    genderUnisex: 'Унисекс',
    notes: 'Ноты',
    topNotes: 'Верхние ноты',
    heartNotes: 'Средние ноты',
    baseNotes: 'Базовые ноты',
    viewAll: 'Смотреть все ароматы',
    homeTitle: 'Искусство минимализма',
    homeSubtitle: 'Найдите свой идеальный аромат.',
    shopCollection: 'В каталог',
    scentFamilies: 'Семейства ароматов',
    familyFloral: 'Цветочные',
    familyOriental: 'Восточные',
    familyWoody: 'Древесные',
    familyFresh: 'Свежие',
    familyCitrus: 'Цитрусовые',
    familySpicy: 'Пряные',
    familyLeather: 'Кожаные',
    familyGourmand: 'Гурманские',
    familyChypre: 'Шипровые',
    familyFougere: 'Фужерные',
    allFamilies: 'Все семейства',
    leaveReview: 'Оставить отзыв',
    name: 'Имя',
    rating: 'Оценка',
    comment: 'Ваш отзыв',
    submit: 'Отправить',
    reviewSuccess: 'Отзыв отправлен и ожидает модерации',
    noReviews: 'Пока нет отзывов об этом товаре',
    toggleTheme: 'Сменить тему',
    toggleLanguage: 'Сменить язык',
    allRightsReserved: 'Все права защищены.',
    noHeroContent: 'Нет настроенного контента для главного экрана',
    ourCollection: 'Наша коллекция',
    exploreCatalog: 'Исследуйте наш полный каталог минималистичных ароматов.',
    noProductsFound: 'Не найдено товаров по запросу',
    needAssistance: 'Нужна помощь?',
    leaveDetails: 'Оставьте свои данные, и наш эксперт по ароматам свяжется с вами, чтобы помочь найти идеальный парфюм.',
    requestReceived: 'Заявка получена',
    managerContact: 'Наш менеджер свяжется с вами в ближайшее время.',
    phoneNumber: 'Номер телефона',
    messageOptional: 'Сообщение (необязательно)',
    failedToSend: 'Не удалось отправить заявку. Пожалуйста, попробуйте еще раз.',
    requestCallback: 'Заказать звонок',
    placeholderName: 'Иван Иванов',
    placeholderPhone: '+375 (29) 000-00-00',
    placeholderMessage: 'Я ищу древесный аромат...',
    orderSuccess: 'Заказ оформлен!',
    orderSuccessDesc: 'Наш менеджер свяжется с вами для подтверждения заказа.',
    scentNotFound: 'Аромат не найден',
    scentNotFoundDesc: 'Как мимолетная верхняя нота, страница, которую вы ищете, растворилась в воздухе. Возможно, формула была изменена или аромат снят с производства.',
    returnToBoutique: 'Вернуться в бутик',
    exclusiveVault: 'Эксклюзивное хранилище',
    exclusiveVaultDesc: 'Доступ к этой редкой эссенции ограничен. У вас нет нужных нот для входа в эту частную коллекцию. Пожалуйста, предъявите свои учетные данные на входе.',
    presentCredentials: 'Предъявить учетные данные',
    filters: 'Фильтры',
    gender: 'Пол',
    sortBy: 'Сортировка',
    reset: 'Сбросить',
    apply: 'Применить',
    brand: 'Бренд',
    wishlist: 'Избранное',
    emptyWishlist: 'Ваш список избранного пуст',
    youMayAlsoLike: 'Вам может понравиться',
    recentlyViewed: 'Вы недавно смотрели',
    newsletterTitle: 'Подпишитесь на новости',
    newsletterDesc: 'Узнавайте первыми о новых ароматах и эксклюзивных предложениях.',
    subscribe: 'Подписаться',
    emailPlaceholder: 'Ваш email',
    newsletterSuccess: 'Вы успешно подписались!',
    perfume: 'Духи',
    eauDeToilette: 'Туалетная вода',
    cologne: 'Одеколон',
    oil: 'Масляные духи',
    categories: 'Категории',
  },
  be: {
    catalog: 'Каталог',
    about: 'Пра нас',
    reviews: 'Водгукі',
    contacts: 'Кантакты',
    cart: 'Кошык',
    addToCart: 'У кошык',
    checkout: 'Аформіць заказ',
    emptyCart: 'Ваш кошык пусты',
    total: 'Усяго',
    currency: 'BYN',
    backToCatalog: 'Назад у каталог',
    notFound: 'Тавар не знойдзены',
    search: 'Пошук водараў...',
    allBrands: 'Усе брэнды',
    sortNameAsc: 'Назва (А-Я)',
    sortNameDesc: 'Назва (Я-А)',
    sortPriceAsc: 'Спачатку танней',
    sortPriceDesc: 'Спачатку даражэй',
    genderAll: 'Усе',
    genderMale: 'Мужчынскія',
    genderFemale: 'Жаночыя',
    genderUnisex: 'Унісекс',
    notes: 'Ноты',
    topNotes: 'Верхнія ноты',
    heartNotes: 'Сярэднія ноты',
    baseNotes: 'Базавыя ноты',
    viewAll: 'Глядзець усе водары',
    homeTitle: 'Мастацтва мінімалізму',
    homeSubtitle: 'Знайдзіце свой ідэальны водар.',
    shopCollection: 'У каталог',
    scentFamilies: 'Сямействы водараў',
    familyFloral: 'Кветкавыя',
    familyOriental: 'Усходнія',
    familyWoody: 'Драўняныя',
    familyFresh: 'Свежыя',
    familyCitrus: 'Цытрусавыя',
    familySpicy: 'Пряныя',
    familyLeather: 'Скураныя',
    familyGourmand: 'Гурманскія',
    familyChypre: 'Шыправыя',
    familyFougere: 'Фужэрныя',
    allFamilies: 'Усе сямействы',
    leaveReview: 'Пакінуць водгук',
    name: 'Імя',
    rating: 'Ацэнка',
    comment: 'Ваш водгук',
    submit: 'Адправіць',
    reviewSuccess: 'Водгук адпраўлены і чакае мадэрацыі',
    noReviews: 'Пакуль няма водгукаў аб гэтым тавары',
    toggleTheme: 'Змяніць тэму',
    toggleLanguage: 'Змяніць мову',
    allRightsReserved: 'Усе правы абаронены.',
    noHeroContent: 'Няма наладжанага кантэнту для галоўнага экрана',
    ourCollection: 'Наша калекцыя',
    exploreCatalog: 'Даследуйце наш поўны каталог мінімалістычных водараў.',
    noProductsFound: 'Не знойдзена тавараў па запыце',
    needAssistance: 'Патрэбна дапамога?',
    leaveDetails: 'Пакіньце свае дадзеныя, і наш эксперт па водарах звяжацца з вамі, каб дапамагчы знайсці ідэальны парфюм.',
    requestReceived: 'Заяўка атрымана',
    managerContact: 'Наш менеджар звяжацца з вамі ў бліжэйшы час.',
    phoneNumber: 'Нумар тэлефона',
    messageOptional: 'Паведамленне (неабавязкова)',
    failedToSend: 'Не ўдалося адправіць заяўку. Калі ласка, паспрабуйце яшчэ раз.',
    requestCallback: 'Замовіць званок',
    placeholderName: 'Іван Іваноў',
    placeholderPhone: '+375 (29) 000-00-00',
    placeholderMessage: 'Я шукаю драўняны водар...',
    orderSuccess: 'Заказ аформлены!',
    orderSuccessDesc: 'Наш менеджар звяжацца з вамі для пацверджання замовы.',
    scentNotFound: 'Водар не знойдзены',
    scentNotFoundDesc: 'Як мімалётная верхняя нота, старонка, якую вы шукаеце, растварылася ў паветры. Магчыма, формула была зменена або водар зняты з вытворчасці.',
    returnToBoutique: 'Вярнуцца ў буцік',
    exclusiveVault: 'Эксклюзіўнае сховішча',
    exclusiveVaultDesc: 'Доступ да гэтай рэдкай эсэнцыі абмежаваны. У вас няма патрэбных нот для ўваходу ў гэтую прыватную калекцыю. Калі ласка, прад\'явіце свае ўліковыя дадзеныя на ўваходзе.',
    presentCredentials: 'Прад\'явіць уліковыя дадзеныя',
    filters: 'Фільтры',
    gender: 'Пол',
    sortBy: 'Сартаванне',
    reset: 'Скінуць',
    apply: 'Ужыць',
    brand: 'Брэнд',
    wishlist: 'Выбранае',
    emptyWishlist: 'Ваш спіс выбранага пусты',
    youMayAlsoLike: 'Вам можа спадабацца',
    recentlyViewed: 'Вы нядаўна глядзелі',
    newsletterTitle: 'Падпішыцеся на навіны',
    newsletterDesc: 'Даведвайцеся першымі пра новыя водары і эксклюзіўныя прапановы.',
    subscribe: 'Падпісацца',
    emailPlaceholder: 'Ваш email',
    newsletterSuccess: 'Вы паспяхова падпісаліся!',
    perfume: 'Духі',
    eauDeToilette: 'Туалетная вада',
    cologne: 'Адэкалон',
    oil: 'Масляныя духі',
    categories: 'Катэгорыі',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'ru';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
